### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/app/.autogenstudio/files/'

### ISSUE THREAD

**Issue by fahadshery** [lludlow/autogen-studio#51]
Hi,

here is my `docker-compose.yml` file:
```
services:
  autogen-studio:
    image: ghcr.io/lludlow/autogen-studio
    environment:
      - OPENAI_API_KEY=YOUR_API_KEY
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data:/app/.autogenstudio
    # ports:
    #   - 8081:8081
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.autogen-studio.rule=Host(`autogen.local.example.com`)"
      - "traefik.http.routers.autogen-studio.entrypoints=https"
      - "traefik.http.routers.autogen-studio.tls=true"
      - "traefik.http.routers.autogen-studio.tls.certresolver=cloudflare"
      - "traefik.http.services.autogen-studio.loadbalancer.server.port=8081"
      - "traefik.http.routers.autogen-studio.middlewares=default-headers@file"

networks:
  traefik:
    external: true
```

I am getting the error: 
```
snip...
│   276 │   files_static_root = os.path.join(app_root, "files/")               │
│   277 │   static_folder_root = os.path.join(app_file_path, "ui")             │
│   278 │                                                                      │
│ ❱ 279 │   os.makedirs(files_static_root, exist_ok=True)                      │
│   280 │   os.makedirs(os.path.join(files_static_root, "user"), exist_ok=True │
│   281 │   os.makedirs(static_folder_root, exist_ok=True)                     │
│   282 │   folders = {                                                        │
│                                                                              │
│ ╭───────────────────────────────── locals ─────────────────────────────────╮ │
│ │      app_file_path = '/app/venv/lib/python3.10/site-packages/autogenstu… │ │
│ │           app_root = '/app/.autogenstudio'                               │ │
│ │           env_file = '/app/.autogenstudio/.env'                          │ │
│ │  files_static_root = '/app/.autogenstudio/files/'                        │ │
│ │ static_folder_root = '/app/venv/lib/python3.10/site-packages/autogenstu… │ │
│ ╰──────────────────────────────────────────────────────────────────────────╯ │
│                                                                              │
│ /usr/local/lib/python3.10/os.py:225 in makedirs                              │
│                                                                              │
│    222 │   │   if tail == cdir:           # xxx/newdir/. exists if xxx/newdi │
│    223 │   │   │   return                                                    │
│    224 │   try:                                                              │
│ ❱  225 │   │   mkdir(name, mode)                                             │
│    226 │   except OSError:                                                   │
│    227 │   │   # Cannot rely on checking for EEXIST, since the operating sys │
│    228 │   │   # could give priority to other errors like EACCES or EROFS    │
│                                                                              │
│ ╭──────────────── locals ─────────────────╮                                  │
│ │ exist_ok = True                         │                                  │
│ │     head = '/app/.autogenstudio'        │                                  │
│ │     mode = 511                          │                                  │
│ │     name = '/app/.autogenstudio/files/' │                                  │
│ │     tail = 'files'                      │                                  │
│ ╰─────────────────────────────────────────╯                                  │
╰──────────────────────────────────────────────────────────────────────────────╯
PermissionError: [Errno 13] Permission denied: '/app/.autogenstudio/files/'
```
