### ISSUE TITLE
autogen with reverse proxy

### ISSUE THREAD

**Issue by fahadshery** [lludlow/autogen-studio#58]
Hi,

I modified your Dockerfile with the following to better manage permissions:
```
# Use python 3.10 slim image as the base
FROM python:3.12-slim

# Set the working directory in the container
WORKDIR /app

# Define environment variables for UID and GID and local timezone
ENV PUID=${PUID:-1000}
ENV PGID=${PGID:-1000}

# Create a group with the specified GID
RUN groupadd -r "${PGID}" autogen

# Create a user with the specified UID and GID
RUN useradd -r -s /bin/bash -d /app -u "${PUID}" -g "${PGID}" autogen

# Create a new user and group 'autogen'
#RUN groupadd -r autogen && \
#    useradd -r -g autogen -d /app -s /bin/bash autogen

# Change ownership of the /app directory to autogen
RUN chown autogen:autogen /app

# Set the home directory for the autogen user
ENV HOME=/app

# Change to the autogen user
USER autogen

# Copy the requirements.txt file and install Python dependencies
COPY --chown=autogen:autogen requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port the app runs on
EXPOSE 8081

# Set the default command to run when starting the container
ENTRYPOINT ["autogenstudio", "ui", "--host", "0.0.0.0", "--port", "8081"]
```

Then created the following docker-compose:
```
services:
  autogen-studio:
    image: ghcr.io/lludlow/autogen-studio
    container_name: autogen
    environment:
      - OPENAI_API_KEY=YOUR_API_KEY
    volumes:
      - ./data:/app/.autogenstudio
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.autogen.rule=Host(`autogen.local.example.com`)"
      - "traefik.http.routers.autogen.entrypoints=https"
      - "traefik.http.routers.autogen.tls=true"
      - "traefik.http.routers.autogen.tls.certresolver=cloudflare"
      - "traefik.http.services.autogen.loadbalancer.server.port=8081"
      - "traefik.http.routers.autogen.middlewares=default-headers@file"
        #    ports:
        #- 8081:8081
networks:
  traefik:
    external: true
```

when I do:
```
docker compose up -d --build --force-recreate --remove-orphans
```
I am getting the following error:
```
[+] Running 0/1
 ⠹ Container autogen  Starting                                                                                                            5.2s
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "autogenstudio": executable file not found in $PATH: unknown
```
